name:                hs-api
version:             0.1.0.0
github:              "hajlaoui-nader/hs-api"
license:             BSD3
author:              "Nader Hajlaoui"
maintainer:          "hajlaoui.nader@gmail.com"
copyright:           "2019 Nader"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Haskell servant api example
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hajlaoui-nader/hs-api#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- transformers
- aeson
- wai
- warp

library:
  source-dirs: src

executables:
  hs-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-api

tests:
  hs-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-api
    - servant-client
    - warp >= 3.2.4
    - http-client
    - http-types
